name: rtsp_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_vlc_player: ^7.4.1
  go_router: ^13.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
